exclude = ["venv*"]
line-length = 99
target-version = "py38"
lint.ignore = [
    "PLR2004",
    "D104",
    "D107",
    "C901",
]
lint.select = [
  "ARG", # flake8-unused args
  "B",   # bandit
  "C",   # complexity
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings
  "F",   # pyflakes
  "I",   # isort
  "PT",  # flake8-pytest
  "RUF", # ruff base config
  "SIM", # flake-simplify
  "UP",  # pyupgrade
  "YTT", # flake8-2020
  ]
[lint.pydocstyle]
convention = "pep257"
